changelog:
  categories:
    - title: "New Features"
      labels: ["enhancement", "feature"]
    - title: "Bug Fixes"
      labels: ["bug", "fix"]
    - title: "Dependencies"
      labels: ["dependencies"]
    - title: "Documentation"
      labels: ["documentation"]
    - title: "Maintenance"
      labels: ["chore", "maintenance", "refactor"]
  exclude:
    labels: ["skip-changelog"]
