# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: config/docs_conf.py
  fail_on_warning: false

# Set the version of Python and requirements
# Project supports Python >=3.9, and 3.13 is fully supported in CI
python:
  version: "3.13"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  pip_install: true

# Build additional formats
formats:
  - pdf
  - epub

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

# Requirements file
requirements_file: config/requirements.txt

# Documentation directory
docs_dir: docs
