build:
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
          - command: python -m pytest --cov=custom_components.imou_life --cov-report=xml:coverage.xml tests/
            coverage:
              file: coverage.xml
              format: py-cc

filter:
  paths:
    - "custom_components/imou_life/*"
  excluded_paths:
    - "tests/*"
    - "docs/*"
    - "config/*"
    - "tools/*"

checks:
  python:
    code_rating: true
    duplicate_code: true

coding_style:
  python:
    indentation:
      general:
        use_tabs: false
        size: 4
    spaces:
      around_operators:
        concatenation: true
        assignment: true
      other:
        after_comma: true

tools:
  external_code_coverage:
    timeout: 600
