build:
  environment:
    python: 3.11
  nodes:
    analysis:
      dependencies:
        before:
          - pip install -r config/requirements_test.txt
      tests:
        override:
          - py-scrutinizer-run
          - command: python -m pytest --cov=custom_components.imou_life --cov-report=xml:coverage.xml tests/
            coverage:
              file: coverage.xml
              format: py-cc

filter:
  paths:
    - "custom_components/imou_life/*"
  excluded_paths:
    - "tests/*"
    - "docs/*"
    - "config/*"
    - "tools/*"

checks:
  python:
    code_rating: true
    duplicate_code: true

tools:
  external_code_coverage:
    timeout: 600
