name: Publish a new release

on:
  workflow_dispatch:

jobs:
  draft_release:
    name: Release Drafter
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      ACTIONS_STEP_DEBUG: false
      ACTIONS_RUNNER_DEBUG: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.1

      - name: Get integration name
        id: information
        shell: bash
        run: |
          name=$(find custom_components/ -type d -maxdepth 1 | tail -n 1 | cut -d "/" -f2)
          echo "name: $name"
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Get integration version from manifest
        id: version
        shell: bash
        run: |
          version=$(jq -r '.version' custom_components/${{ steps.information.outputs.name }}/manifest.json)
          echo "version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: ${{ steps.version.outputs.version }}
          path: ./CHANGELOG.md

      - name: Create zip file for the integration
        run: |
          cd "${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}"
          zip ${{ steps.information.outputs.name }}.zip -r ./
          mv ${{ steps.information.outputs.name }}.zip "${{ github.workspace }}/"
          ls -la "${{ github.workspace }}/"

      - name: Draft GitHub Release
        id: draft_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "Pre-release - ${{ steps.version.outputs.version }}"
          tag_name: "v${{ steps.version.outputs.version }}"
          body: |
            ## Pre-release - ${{ steps.version.outputs.version }}

            This is a pre-release version. Please test thoroughly before using in production.

            ### Changes
            ${{ steps.changelog_reader.outputs.changes }}

            ### Installation
            1. Download the `${{ steps.information.outputs.name }}.zip` file from this release
            2. Extract to your Home Assistant `custom_components` directory
            3. Restart Home Assistant
            4. Add the integration via Settings > Devices & Services

            ### Requirements
            - Home Assistant 2023.8.0 or later
            - imouapi==1.0.15

          files: |
            ${{ github.workspace }}/${{ steps.information.outputs.name }}.zip
          draft: true
          prerelease: true
