name: Test

on:
  push:
    branches: [ main, master ]  # Only run on main/master pushes
  pull_request:  # Runs on ALL PRs from ANY branch

env:
  DEFAULT_PYTHON: 3.13

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    name: Pre-commit
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Python modules
        run: |
          pip install --constraint=.github/workflows/constraints.txt pre-commit black flake8 isort

      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure --color=always

  tests:
    runs-on: "ubuntu-latest"
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12, 3.13]
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v5
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip install -r config/requirements_test.txt
      - name: Tests suite
        run: |
          pytest \
            --asyncio-mode=auto \
            --durations=10 \
            --cov=custom_components.imou_life \
            --cov-config=config/.coveragerc \
            --cov-report=lcov \
            --cov-report=term-missing \
            tests
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: HACS validation
        uses: hacs/action@22.5.0
        with:
          category: "integration"
          ignore: brands

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
